WebApp2/WebApplication1/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class GuestController : Controller
    {
        // GET: Guest
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(string uname,string pass)
        {
            StpDBEntities db = new StpDBEntities();
            tblUser user = db.tblUsers.SingleOrDefault(x => x.fname==uname && x.lname==pass);
            if (user != null)
            {
                Session["uname"] = uname;
                return RedirectToAction("dashboard");
            }
            else
            {
                ViewBag.msg = "invalid input credentials";
            }
            return View();
        }

        public ActionResult DashBoard()
        {
            if (Session["uname"] != null)
            {
                string uname = Session["uname"].ToString();
                ViewBag.msg = "hello" + uname + ",welcome";
            }
            return View();
        }
        [HttpPost]
        public ActionResult DashBoard(string bp)
        {
            return RedirectToAction(bp);
        }


        public ActionResult Confidential()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Confidential(string bp)
        {
            return RedirectToAction(bp);
        }
        public ActionResult Logout()
        {
            return View();
        }
    }
}

WebApp2/WebApplication1/Controllers/PostBackDemosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class PostBackDemosController : Controller
    {
        // GET: PostBackDemos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Ex1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ex1(string ename)
        {
            ViewBag.msg = "hello" + ename;
            return View();
        }



        public ActionResult Ex2()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ex2(string b1)
        {
            ViewBag.msg = b1;
            return View();
        }


        public ActionResult Ex3()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ex3(string b1,int y,int x)
        {
            if (b1.Equals("add"))
            {
                ViewBag.msg = "addition : = " + (x + y);
            }
            else
            {
                ViewBag.msg = "subtraction : = " + (x - y);
            }
            return View();
        }



        public ActionResult Ex4()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ex4(string name, string gender)
        {
            ViewBag.msg = "hello: " + gender + name;
            return View();
        }


        public ActionResult Ex5()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ex5(string name, string check)
        {
            ViewBag.msg = "hello: " + name+" you have "+check+" checked";
            return View();
        }


        public ActionResult Ex6()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ex6(string name, string[] check)
        {
            ViewBag.msg = "hello: " + name + " you have these : ";

            string msg = string.Empty;
            foreach (string s in check)
            {
                if (!s.Equals("false"))
                {
                    msg += s+"<br/>";
                }
            }
            ViewBag.msg = msg;
            return View();
        }


        public ActionResult Ex8()
        {
            List<string> op = new List<string> { "update", "delete", "retrieve" };
            TempData["op"] = op;
            return View();
        }
        [HttpPost]
        public ActionResult Ex8(string op)
        {

            ViewBag.msg = op;
            return View();
        }

        public ActionResult Ex9()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Ex9(string b1)
        {

           
                return RedirectToAction(b1);
          
        }
    }
}

WebApp2/WebApplication1/Views/Guest/Confidential.cshtml
@{
    ViewBag.Title = "Confidential";
}

<h2>Confidential</h2>


@Html.ActionLink("go to dashboard", "dashboard", "Guest")
@using (Html.BeginForm())
{
    <br />
    <input type="submit" name="bp" value="logout" />
}

WebApp2/WebApplication1/Views/Guest/DashBoard.cshtml
@{
    ViewBag.Title = "DashBoard";
}

<h2>DashBoard</h2>


@Html.ActionLink("go to confidential", "Confidential", "Guest") <br />

@Html.ActionLink("go to postback demo ", "Index", "PostBackDemos")


@using (Html.BeginForm())
{
    <br />
    <input type="submit" name="bp" value="logout" />
}

@ViewBag.msg;

WebApp2/WebApplication1/Views/Guest/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home page</h2>


@Html.ActionLink("Sign-in", "Login", "Guest")

WebApp2/WebApplication1/Views/Guest/Login.cshtml
@{
                /**/

                ViewBag.Title = "Login";
}

<h2>Login</h2>

<br />


@using (Html.BeginForm())
{
@Html.Label("uname", "enter email   :  ")
@Html.TextBox("uname")<br />

@Html.Label("pass", "enter password   :  ")
@Html.TextBox("pass")<br />


    <br/>
    <input type="submit"  value="Log-In" />
}


@ViewBag.msg

WebApp2/WebApplication1/Views/Guest/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>

@Html.ActionLink("login", "Login", "Guest")